name = "youtopia-worker"
main = "worker/worker.js"
compatibility_date = "2023-08-01"

[vars]
GOOGLE_CLIENT_ID = "450557144881-necfmjts3gdvkp5o6a7dsar6o34ns2mf.apps.googleusercontent.com"
FIREBASE_PROJECT_ID = "youtopia-search-prod"
MISTRAL_API_KEY = "TcTEMn3IxCjzq759GMAtTaLevjpjJqR2" # Placeholder - Replace with your actual Mistral API Key

[[kv_namespaces]]
binding = "YOUTOPIA_DATA"
id = "0a5569479dc94d15aa6e45879acf7393"

[[kv_namespaces]]
binding = "YOUTOPIA_CONFIG"
id = "4a4e8de04c8240e994b8986536785345"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true