name = "youtopia-worker"
main = "worker/worker.js"
compatibility_date = "2023-08-01"

[vars]
MISTRAL_API_KEY = "${MISTRAL_API_KEY}"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "16f929421e4342b8bf0273c75c7638bc"